---
name: snapcast-server
version: "0.25"
slug: snapcastserver
description: Snapcast Server
init: false
map:
  - share:rw
options:
  stream:
    streams:
      - pipe:///share/snapfifo/librespot?name=SpotifyConnect&sampleformat=44100:16:2
      - pipe:///share/snapfifo/mopidy?name=Mopidy&sampleformat=44100:16:2
      - tcp://0.0.0.0?port=4953&name=snapbroadcast
    buffer: "1000"
    codec: flac
    send_to_muted: "false"
    sampleformat: "48000:16:2"
  http:
    enabled: "true"
    doc_root: "/usr/share/snapserver/snapweb"
  tcp:
    enabled: "true"
  logging:
    enabled: "true"
  server:
    threads: "-1"
    datadir: "/share/snapcast/"
schema:
  stream:
    streams:
      - str
    buffer: int
    codec: str
    send_to_muted: str
    sampleformat: str
  http:
    enabled: str
    doc_root: str
  tcp:
    enabled: str
  logging:
    enabled: str
  server:
    threads: int
    datadir: str
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
  6980/udp: 6980
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
